dist: bionicj
language: python
python: "3.6"
cache:
  - pip: true
  - directories:
    - "$HOME/.cache/pypoetry"
before_install:
  - pip install poetry
install:
  - make

# This repository is so small that breaking linting, testing, etc. into jobs is not efficient
script:
  - make check
